### ISSUE TITLE
Debuffs are not showing

### ISSUE THREAD

**Issue by RShakleford** [baharms/enemybar2#4]
I recently installed Enemybar2 and for some reason I can get all of the settings to show except for the debuffs. I have it set to true in the settings and even use the command in game just in case but nothing. Can I get some help with this please?

**Comment by Lenix005** [comment]
I have the same issue

**Comment by AkadenTK** [comment]
The debuffs that EB2 shows are very specific: Bind, sleep, petrify and stun.  No others will show. The main reason is that it's actually quite hard to track debuffs, and it's not always terribly accurate. So I restricted it to some important debuffs that would help me not wake or break the bind of an enemy.

One day I may return to add more debuffs to the tracking.

**Comment by Lenix005** [comment]
Thank you for your reply, maybe its possible to extract it from the chat log? like xxx receives the effct of.... and ... looses the effect of.... ?

Anyway have a great day and thank you for the great work
On 7/25/2022 3:28:55 PM, AkadenTK ***@***.***> wrote:
The debuffs that EB2 shows are very specific: Bind, sleep, petrify and stun. No others will show. The main reason is that it's actually quite hard to track debuffs, and it's not always terribly accurate. So I restricted it to some important debuffs that would help me not wake or break the bind of an enemy.
One day I may return to add more debuffs to the tracking.

**Comment by AkadenTK** [comment]
It's a bit more complicated than that. Some spells do not tell the client via packets that the debuff was even applied. There's a whole library in windower that extracts action messages from packets. And some info just never comes to the client. Notably: other PC's debuffs and most (if not all) BLU spells just do not register. We can map spell name to debuff, but we won't know that it applied unless there's some effect that's outwardly noticeable (paralyze comes to mind). 

So it's pretty frustrating to get debuff information. There's a plugin that tracks the timers etc. It works really well for what info we have, but it's not easy to do and I don't want to repeat the effort (and with likely poorer results)

**Comment by Lenix005** [comment]
Thank you for your reply, I understand it can be hard I made some addons for ffxiv back in the day "Overlaylines" but used ACT as a backbone. I have the timers but they are not accurate at all and not taking in account my gear, I wish I could find the file to manually edit my duration times but I still did not find them since it's a script and not a add on. But thank you again for your time and if there is something I can do to help, like testing or logging data feel free to hit me up.
On 7/25/2022 5:06:29 PM, AkadenTK ***@***.***> wrote:
It's a bit more complicated than that. Some spells do not tell the client via packets that the debuff was even applied. There's a whole library in windower that extracts action messages from packets. And some info just never comes to the client. Notably: other PC's debuffs and most (if not all) BLU spells just do not register. We can map spell name to debuff, but we won't know that it applied unless there's some effect that's outwardly noticeable (paralyze comes to mind).
So it's pretty frustrating to get debuff information. There's a plugin that tracks the timers etc. It works really well for what info we have, but it's not easy to do and I don't want to repeat the effort (and with likely poorer results)
